[package]
name = "calcit-wasm-play"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# calcit_runner = { path="../calcit-runner.rs" }
calcit_runner = "0.5.0-a6"
wasm-bindgen = "*"
im = "15.0.0"
console_error_panic_hook = "*"
web-sys = { version="0.3.5", features=[ "console" ] }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
debug = true

