[package]
name = "calcit-wasm-play"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# calcit_runner = { path="../calcit_runner.rs" }
calcit_runner = "0.5.7"
wasm-bindgen = "*"
console_error_panic_hook = "*"
web-sys = { version="0.3.5", features=[ "console" ] }
im_ternary_tree = "=0.0.1-a7"
rpds = "0.10.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
debug = true
