[package]
name = "calcit-wasm-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# calcit = { path="../calcit" }
calcit = "0.5.48"
rpds = "0.12.0"
im_ternary_tree = "0.0.10"
wasm-bindgen = "0.2.81"
console_error_panic_hook = "*"
web-sys = { version="0.3.58", features=[ "console" ] }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
debug = true
