on:
  push:
    branches:
      - main

  pull_request: {}

name: Upload

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: calcit-lang/setup-cr@0.0.3
        with:
          version: '0.8.50'

      - run: wasm-pack build -t web

      - run: yarn

      - name: "compiles to js"
        run: >
          caps --ci && cr --emit-js --once
          && yarn && yarn vite build --base=./

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "dist/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
